apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: datastreaming
  labels:
    app: kafka-producer
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: debezium-container
          image: glmtduh/debezium:1.7
          imagePullPolicy: IfNotPresent
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: CONNECT_LOG4J_LOGGERS
              value: "DEBUG,appender,stdout"
            - name: CONNECT_LOG4J_LOGGER_ORG_APACHE_KAFKA_CONNECT_RUNTIME_REST
              value: "WARN"
            - name: CONNECT_LOG_LEVEL
              value: "DEBUG"
            - name: LOG_ENABLED
              value: "true"
          ports:
            - containerPort: 8083
          volumeMounts:
          - mountPath: /kafka/logs
            name: debezium-data
      volumes:
      - name: debezium-data
        persistentVolumeClaim:
          claimName: datastream-pvc
