apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ngixn-demo
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ngixn-demo
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: nginx
          image: demo:latest
          ports:
          - containerPort: 80
          imagePullPolicy: IfNotPresent