name: production
on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  build:
    runs-on: [self-hosted]
    if: contains(github.event.head_commit.message, '#build') || contains(github.event.head_commit.message, '#build&deploy')
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build-docker-image
        run: |-
          docker build -t test:latest .
          docker image tag test:latest registry.local/test
          docker image push registery.local/test
  deploy:
    runs-on: [self-hosted]
    if: contains(github.event.head_commit.message, '#deploy')
    env:
      KUBECONFIG: kube.conf
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: deploy
        run: |-
          kubectl apply -f k8s-uat.yaml
          kubectl -n prod rollout restart statefulset test
  cleanup:
    runs-on: [self-hosted]
    needs: [build, build-deploy, deploy]
    if: ${{ always() }}
    steps:
      - name: Cleanup
        if: ${{ always() }}
        run: |
          echo "Cleaning up"
          rm -rf "${{ github.workspace }}"
